server:
  port: 9898
spring:
  application:
    name: stock-market-service
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/stockinfo
    username: root
  jpa:
    hibernate:
      ddl-auto: create
